### ISSUE TITLE
Question about symbolic agent in the experiment

### ISSUE THREAD

**Issue by realliyifei** [dki-lab/Pangu#13]
I am confused about the symbolic agent in the 3 datasets in the experiment: are they just the off-the-shelf entity linkers from https://github.com/dki-lab/Pangu/tree/main/el_results ?

**Comment by entslscheia** [comment]
Thanks for your interest in our work!
The symbolic agent is basically what determines the candidate plans/programs from the environment (e.g., KB here); they are entity linkers.
You may find the detailed implementation in [get_initial_programs](https://github.com/dki-lab/Pangu/blob/5caf0a5be8f6cf90480632d296b973248fffc677/utils/kb_environment.py#L908C7-L908C7) and [get_admissible_programs](https://github.com/dki-lab/Pangu/blob/5caf0a5be8f6cf90480632d296b973248fffc677/utils/kb_environment.py#L576C9-L576C24).

**Comment by realliyifei** [comment]
Thank you for your reply, I quite enjoy reading the paper! I have two follow-up questions:
1. The paper seems to assume the symbolic agent is oracle / perfect, is that correct? This paradigm would be limited when the symbolic agent is imperfect or even not existing — which is common in real applications
2. The beam search seems to require execution at each step to determine the next states, but in lots of scenarios we can just execute once and cannot go back (e.g. robot to make food), so I think the beam search only works when the environment is executable and retractable?

**Comment by entslscheia** [comment]
1. Conceptually, a symbolic agent can be an abstract representation of anything that can propose candidate plans from the environment. By "oracle / perfect", are you indicating that the proposed plans always include the gold (sub)plans? If so, I think your comment is mostly correct: for grounding to digital environments (like a KB or a DB), designing an "oracle" should be relatively easy, while for grounding to physical environments like robot planning, it's hard to guarantee that we can always accurately propose candidate plans from the environment (e.g., due to the loss in visual recognition). In that case, probabilistic representation of the candidates might be necessary (like in SayCan [1]).
2. I think this is a very interesting question. Here's some personal take: for scenarios involving non-reversible state changes (e.g., once a tomato is sliced, we will not be able to recover from it), doing search can be quite tricky. We may just do greedy search (i.e., beam size=1) with no backtracking. However, if the actions are actually reversible (e.g., navigating in a room), beam search is still possible, but it requires more costly backtracking in the physical environment [2]. To sum up, while the specific search framework presented in our paper might not be universally applicable, the core idea of allowing the language model to focus on discrimination—by separating it from a symbolic agent that suggests candidate plans from the environment—retains broad relevance.

Hope it helps!

[1] https://arxiv.org/abs/2204.01691
[2] https://arxiv.org/abs/1903.02547

**Comment by realliyifei** [comment]
Thank you for such insightful replies!
