### ISSUE TITLE
dataset specific vocabs

### ISSUE THREAD

**Issue by gourango01** [dki-lab/Pangu#17]
Could you pls share the code to create dataset-specific vocab files (present in utils/vocab_files)?
And if I am not wrong, these vocab files are used to prune the search space during Candidate Plan Enumeration?

**Comment by entslscheia** [comment]
Hi @gourango01,

Thank you for your interest in Pangu and sorry about the late response!

The vocab is just the full set of schema items. For GraphQ, we need to include all the schema items from Freebase; for GrailQA, the vocab includes all schema items from Freebase Commons according to the original paper of GrailQA; for WebQSP, because it's mostly an i.i.d. setup, we can choose use it's training set to construct the vocabulary.
However, we found that the affect of vocab files is minimal. You can basically use all schema items from Freebase for all datasets. The difference of vocab size is not a bottleneck.

Best,
Yu Gu
